name: Stage
on:
  workflow_run:
    workflows: ["CI"]
    types: 
      - completed
    branches:
      - 'stage'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
        packages: write
        contents: read
    steps:
        - uses: actions/checkout@v3
          with: 
            ref: 'stage'
        - uses: actions/setup-node@v3
          with:
            node-version: 16.x
            cache: "npm"                  
            registry-url: https://npm.pkg.github.com/
        - name: Publish to GPR (staging)
          run: npm run ci && npx changeset version && npm publish --tag beta
          env:
              NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
